### ISSUE TITLE
Improve Image Support

### ISSUE THREAD

**Issue by Darth-Raazi** [waterloo-rocketry/omnibus#200]
We currently have an image item but it's pretty bad. We want to improve moving, resizing, positioning, and panning overtop of images. A nice-to-have would be anti-aliasing of some sort so that we can expand and zoom into images without everything becoming a blurry mess. The end goal is to be able to take an image and set it as the "background" of the dashboard.

**Comment by patrick-gu** [comment]
I think a major problem here is that we're using a `QLabel` with a pixmap, so I don't think it'll be possible to get subpixel rendering like this, which I assume is the desired behavior. (i.e., in the gauge item, everything remains crisp no matter how much you zoom in). I wonder if we could use `QPainter` to do that. 

Also, I think it's important to define how we want the image to work. The most configurable I imagine would be having a frame with the image inside, and you can move the image around in the frame, sort of like Google Maps. This would be pretty annoying though because you'd have to configure both the size of the frame and the size of the image. I think that all we reasonably would want is being able to resize and move the image arbitrarily, as that would allow us to set it as a background.
