### ISSUE TITLE
[sinks/globallog] Globallog proper exit

### ISSUE THREAD

**Issue by zangjiucheng** [waterloo-rocketry/omnibus#303]
Current the only way to exit globallog is by ctrl+c which may crash the log file we implement, we hope to develop a hotkey detect to proper exit the globallog.

**Comment by ChrisYx511** [comment]
For future reference
# Use Case Breakdown
As a **test site DAQ operator**;
I would want to be able to ensure that globallog exits properly and that the log file is saved properly to disk;
Because, the logging data is critical for testing and currently the program does not exit cleanly and can even fail to respond to SIGINT.
# Requirements
- Globallog sink MUST close the file handle cleanly on SIGINT, SIGTERM, or any other scenario to prevent file corruption
- Globallog sink MUST display the hotkeys to interrupt logging to the user
